supabase/postgrest-py

- postgrest_py/request_builder.py
- tests/test_filter_request_builder.py
Introduces match command. Addresses #17 
Non-existent
N.A.
> Add Match Command

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Makefile
- postgrest_py/_async/client.py
- postgrest_py/_async/request_builder.py
- postgrest_py/_sync/client.py
- postgrest_py/_sync/request_builder.py
- tests/_async/test_request_builder.py
- tests/_sync/test_request_builder.py
> fix: interpolations errors and other things reported by sourcery-ai

- .pre-commit-config.yaml
Reverts supabase-community/postgrest-py#38
> Revert "Add Sourcery to pre-commit"

- postgrest/base_request_builder.py
Limit rows returned for a foreign table and order by foreign table column.
> limit and order on foreign tables

- Makefile
- postgrest/_async/request_builder.py
- postgrest/_sync/client.py
- postgrest/_sync/request_builder.py
- postgrest/base_request_builder.py
- tests/_async/test_client.py
- tests/_async/test_request_builder.py
- tests/_sync/test_client.py
- tests/_sync/test_request_builder.py
Signed-off-by: Bariq <bariqhibat@gmail.com>
Resolve #94
Note:
1. This is still under development, might need some help and comments on this (cc @dreinon)
> Implementation of `maybe_single`

- postgrest/__init__.py
- pyproject.toml
> chore: update corresponding files for 0.10.4 version bump

- postgrest/_async/request_builder.py
- postgrest/_sync/client.py
- postgrest/_sync/request_builder.py
- postgrest/base_request_builder.py
- postgrest/exceptions.py
- tests/_sync/test_client.py
Related issues: #218, #195, #206 #200
> fix: handle Py311 Validation errors

- postgrest/base_request_builder.py
- tests/_async/test_request_builder.py
Adds the explain() function that is available in the javascript client.
> feat explain

- postgrest/__init__.py
- pyproject.toml
> chore: bump postgrest version to v0.10.7

- .github/workflows/ci.yml
- pyproject.toml
Introduces semver changes similar to: https://github.com/supabase-community/gotrue-py/commit/3c9984b2f89828f304b8f4fa1702b209ef5243bf so that we don't have to manually publish versions
- Added trusted publisher on PyPI
> fix: add semver

- .github/CODEOWNERS
- .github/workflows/ci.yml
> feat: update semver, add CODEOWNERS

- postgrest/_async/request_builder.py
- postgrest/_sync/request_builder.py
> fix: update upsert type

- tests/_async/test_filter_request_builder_integration.py
- tests/_sync/test_filter_request_builder_integration.py
> test: remove skip from rpc with range test

- .github/workflows/ci.yml
Reverts supabase-community/postgrest-py#396
> Revert "chore(deps): bump codecov/codecov-action from 4.1.0 to 4.1.1"

- .github/workflows/ci.yml
- Makefile
Release pipeline fix
Release pipeline is currently broken
This PR should fix the release pipeline.
> chore(ci): update cli workflow

- .github/workflows/ci.yml
Bug fix, feature, docs update, ...
> ci: only run publish if pr title matches keywords

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/conventional-commits.yml
- README.md
Bug fix, feature, docs update, ...
> ci: update default branch to main

- README.md
docs update
Status is noted in README as unstanle
Removed status from README as the library is official and stable now
> chore(docs): remove unstable status from readme

- .github/CODEOWNERS
Removes myself from the codeowners file
> Remove oli from codeowners

- postgrest/_async/client.py
- postgrest/_sync/client.py
- postgrest/base_client.py
> feat: Proxy support

- poetry.lock
- pyproject.toml
- tests/_async/test_filter_request_builder.py
- tests/_sync/test_filter_request_builder.py
> fix: httpx minimum version update

- Makefile
- poetry.lock
- tests/_async/test_client.py
- tests/_sync/test_client.py
Bug fix, feature, docs update, ...
> chore(tests): fix failing tests

- .github/workflows/ci.yml
Bug fix, feature, docs update, ...
> chore(ci): fix missing indentation

- tests/_async/test_filter_request_builder_integration.py
Tests
Missing tests for async client 
Add tests for async client
> test: add rpc get, head and count tests
