.github/workflows/ci-python.yml
.gitignore
postgrest_py/request_builder.py
tests/test_filter_request_builder.py

This fix allows to apply several filters to a single column.
Currently every new filter overrides the previous one (e.g. `builder.gte('x', 10).lte('x', 20)` produces `x=lte.20`), this is due to how `httpx.QueryParams.__set__` works.

Allow multivalued query parameters

---

CHANGELOG.md
postgrest_py/__init__.py
postgrest_py/client.py

Allow setting headers in `PostgrestClient`'s constructor, prepare a solution for #9.

Allow setting headers in PostgrestClient's constructor

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

In this PR we introduce a Code of Conduct as well as Contributing guidelines as per the [community template](
https://github.com/supabase-community/hacktoberfest-hackathon-template/blob/main/LICENSE)

Add Code of Conduct and Contributing guide

---

postgrest_py/utils.py
tests/test_filter_request_builder.py

Signed-off-by: Bariq <bariqhibat@gmail.com>
This should fix https://github.com/supabase-community/supabase-py/issues/37
In this case, I don't think that http libraries that we use provide this URL encoding automatically, that's why the bug occured. Ultimately, it is also desired to assume that our http library does not though.
Ref: https://postgrest.org/en/v7.0.0/api.html

fix bug on sanitizing params

---

postgrest_py/__init__.py
postgrest_py/_async/client.py
postgrest_py/_sync/client.py
postgrest_py/base_client.py

This feature is for evicting the use of the default timeout of httpx. Resolve #72

feat: add timeout as a parameter of clients

---

postgrest_py/base_request_builder.py
tests/_async/test_request_builder.py
tests/_sync/test_request_builder.py

Add tests for response model

---

postgrest_py/exceptions.py

APIError was failing since there are errors that do not contain all properties defined in the code base.

Fix APIError

---

postgrest_py/exceptions.py

fix: make api error properties optionals

---

postgrest_py/base_request_builder.py
tests/_async/test_filter_request_builder.py
tests/_sync/test_filter_request_builder.py

This change fixes https://github.com/supabase-community/postgrest-py/issues/99.
Specifically, this change enables a PostgREST `cs.***` query that searches an Array, such as `[{"foo": "bar"}]`. This aim to to keep the same API as `.cs`/`.cd`, modeled after the [JS library's implementations](https://github.com/supabase/postgrest-js/blob/f6683f1babd471527c87b7b70212a9d1091b6e0e/src/lib/PostgrestFilterBuilder.ts#L206-L250).

feat: add .contains and .contained_by operators to match JS client

---

pyproject.toml

Poetry by default looks for a directory with the same name as the
project as the source directory. However as our project is named
postgrest-py, but we migrated to the postgrest namespace, we need to
explicitly tell poetry where to look for the source code.

fix: include source directory name

---

postgrest/_async/request_builder.py

fix #182, allow insert to support lists as well

fix: update types for insert

---

postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py
postgrest/base_request_builder.py

feat: upsert with on-conflict support

---

.github/workflows/ci.yml
.pre-commit-config.yaml
poetry.lock
postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py
postgrest/base_request_builder.py
pyproject.toml

chore: update pre-commit

---

postgrest/utils.py
tests/_async/test_filter_request_builder.py
tests/_sync/test_filter_request_builder.py
tests/test_utils.py

Bug fix
Nested columns (of the form `foreign_table.column`) are currently escaped which breaks the API exposed by postgrest.
https://github.com/supabase-community/postgrest-py/issues/189
https://github.com/supabase-community/postgrest-py/issues/202
This PR modifies the sanitize_parameters() function so that the `.` character is not escaped anymore.
It also adds some test to verify this behavior.

Fix sanitize_params to correctly resolve nested columns

---

postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py

Bug fix - closes #230 . The maybe_single method now returns None when the query returns 0 rows.
maybe_single errors out on responses with 0 rows, while trying to create a `SingleAPIResponse` with it's `data` field set to None, which pydantic rejects.

`maybe_single` with no matching rows returns None

---

poetry.lock
postgrest/base_request_builder.py
pyproject.toml

Pydantic version update. All the existing test are passing.

Migrate postgrest-py from pydantic v1 to v2.

---

postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py

Bug fix
**Issue** - The `maybe_single` method seems to work when there is a single record in the database matching the query, but if there are no matching results in the database, an error is raised.
https://github.com/supabase-community/supabase-py/issues/511
**Reason** - Error message is been updated in postgREST https://github.com/PostgREST/postgrest/pull/2876
New changes return None when no matching result found in database.

fix: maybe_single return None when no matching result found in database.

---

postgrest/_async/client.py
postgrest/_async/request_builder.py
postgrest/_sync/client.py
postgrest/_sync/request_builder.py
postgrest/base_request_builder.py
postgrest/utils.py

Fixes #200 
This PR makes all the request builders and the APIResponse classes generic;
- The type of the data to be returned by the query can now be passed down the builder chain and into the APIResponse class
- Pydantic then uses this type for any validation to be done
This fixes the issue by using `APIResponse[Any]` as the return type for rpc calls, while using `APIResponse[list[dict[str, Any]]` for other queries.
This also opens us up to (in the future) allowing users to pass in their own pydantic models to the query, so that the response is well-typed.
~~Marked as draft to write more tests~~

feat: generic query builders

---

.github/workflows/ci.yml
.pre-commit-config.yaml
pyproject.toml

Bug fix to stop the pre-commit hook from checking line ending on markdown files, using the correct token to publish a release and correct semantic releases variable names.

fix: pre-commit hook to stop checks on md files

---

postgrest/__init__.py
postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py
postgrest/base_request_builder.py
tests/_async/test_request_builder.py
tests/_sync/test_request_builder.py

Notes:
- Adding a .csv() to the chain will eventually return a  `SingleAPIResposne[str]`, whose `data` field will be the data returned as a CSV string.
- Calling csv() has a similar effect as calling single() - it has to be the last call in the chain (only .execute() can follow it)

feat: add csv() modifier

---

postgrest/_async/client.py

Makes the `.rpc` function synchronous
As `.rpc` was async but it only returned a FilterBuilder, the examples shown in docs would fail saying
```
response = await client.rpc(...).execute()
AttributeError: 'coroutine' object has no attribute 'execute'
sys:1: RuntimeWarning: coroutine 'AsyncPostgrestClient.rpc' was never awaited
``` 
This meant that you'd need to double await, like
```py
response = await (await client.rpc(...)).execute()
```
[Discord help thread](https://discord.com/channels/839993398554656828/1162309992523763783)

fix: make rpc function sync

---

postgrest/base_request_builder.py

Patch the add offset pr in #167  since it seems stale
To test this do: `res = supabase.from_("countries").select("*").limit(5).offset(3).execute()` on the default countries table. You should see that there are 5 entries starting from index 4.
TODO:

feat: add offset

---

poetry.lock
postgrest/__init__.py

Exporting `AsyncRPCFilterRequestBuilder`, `AsyncMaybeSingleRequestBuilder`, `RPCFilterRequestBuilder` and `MaybeSingleRequestBuilder` from the package main namespace
The package wasn't exporting the `AsyncRPCFilterRequestBuilder`, `AsyncMaybeSingleRequestBuilder`, `RPCFilterRequestBuilder` and `MaybeSingleRequestBuilder` from its main namespace
The package now exports the `AsyncRPCFilterRequestBuilder`, `AsyncMaybeSingleRequestBuilder`, `RPCFilterRequestBuilder` and `MaybeSingleRequestBuilder` from its main namespace

fix: add missing exports

---

Makefile
postgrest/base_request_builder.py
pyproject.toml
tests/_async/test_filter_request_builder.py
tests/_sync/test_client.py
tests/_sync/test_filter_request_builder.py

Add alias for range methods
range method names are obscure
range method names match that of the js library and are more verbose

chore: add alias for range methods

---

Makefile
infra/docker-compose.yaml
infra/init.sql
poetry.lock
postgrest/base_request_builder.py
pyproject.toml
tests/_async/client.py
tests/_async/test_filter_request_builder.py
tests/_async/test_filter_request_builder_integration.py
tests/_sync/client.py
tests/_sync/test_filter_request_builder.py
tests/_sync/test_filter_request_builder_integration.py

Add `or` filter along with unit and integration tests
No `or` filter
Has `or` filter

add or filter along with tests

---

postgrest/base_request_builder.py
tests/_async/test_request_builder.py
tests/_sync/test_request_builder.py

Bug fix
`.range` doesn't work with `.rpc` calls as these are POST requests and range only works with GET requests
`.range` now works with `.rpc` calls

update range to use query parameters instead of headers

---

infra/init.sql
postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py
postgrest/base_request_builder.py
tests/_async/test_filter_request_builder_integration.py
tests/_sync/test_filter_request_builder_integration.py

Add additional filters to rpc calls to match that of the JavaScript library.
You currently cannot use `limit`, `range`, `select` and some other filters with a `.rpc` call.
You can now use `limit`, `range`, `select` and some other filters with a `.rpc` call.
The other related PR in the `supabase-py` repo should be merged first https://github.com/supabase-community/supabase-py/pull/702

feat: Add RPC request builder class for additional filters

---

.github/workflows/ci.yml
postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py
postgrest/base_request_builder.py
tests/_async/test_request_builder.py
tests/_sync/test_request_builder.py

Feature / Bug Fix: adding the `default_to_null` parameter for `upsert` and `insert` methods as presented in both JavaScript and Dart/Flutter version of the client.
When doing bulk insert/upsert of rows into the Postgresql table, the missing fields are default to Nulls instead of using the default value of the column. The parameter `default_to_null` allows the user to use default values from the column definition, instead of using Nulls. But this parameter is currently not exposed in the Python client, though they are available in both JavaScript and Dart/Flutter clients.
When `default_to_null = True` (default value), the current behavior withholds, where missing fields from the json payload will be inserted using Null. 
When setting `default_to_null = False` AND user is performing bulk …

Upsert / Insert with default_to_null boolean argument

---

postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py
postgrest/base_request_builder.py

- Tiny fixes and proper code style.

Fixes and style

---

postgrest/base_request_builder.py
tests/_async/test_filter_request_builder.py
tests/_async/test_filter_request_builder_integration.py
tests/_sync/test_filter_request_builder.py
tests/_sync/test_filter_request_builder_integration.py

Update the overlaps feature
`overlaps` currently doesn't cater for timestamp range
`overlaps` now caters for timestamp range

fix: update overlaps to work with timestamp range

---

postgrest/base_request_builder.py

Adding support for Python None type
You cannot use `None` type with the `is_` method.
You can use the `None` type with the `is_` method.

fix: convert None to a string null for the is method

---

postgrest/_async/client.py
postgrest/_sync/client.py

feature update
You can't perform get, head or count on a rpc method
You can perform get, head or count on a rpc method

fix: add get, head and count parameters to the rpc method.

---

postgrest/_async/client.py
postgrest/_sync/client.py

- Add `follow_redirects=True`.
- All other Supabase libs follow redirects by default.

Follow redirects

---

poetry.lock
postgrest/_async/client.py
postgrest/_sync/client.py
pyproject.toml

- Enable HTTP2 when available.

Enable HTTP2

---

postgrest/base_request_builder.py
tests/_async/test_filter_request_builder.py
tests/_sync/test_filter_request_builder.py

Reverts supabase/postgrest-py#461 because it broke functionality of the library. You can see the linked issue for a repro of the issue https://github.com/supabase/postgrest-py/issues/477.

fix: revert sanitize_pattern_param in like and ilike

---

postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py
postgrest/base_request_builder.py
tests/_async/test_request_builder.py
tests/_sync/test_request_builder.py

Fix https://github.com/supabase/postgrest-py/issues/507
- `select` without columns should default to `*`
- add `head` param for select method for when you want to use `HEAD` HTTP method, this is how all other client libs works.

feat: select all columns by default

---

postgrest/base_request_builder.py

- Fix types to use `Option[T]` instead of Unions of Nones.

fix: Types to use Option[T]

---

poetry.lock
pyproject.toml

Install `strenum` package only with Python 3.10 and older
#518

fix(deps) install strenum package only with Python 3.10 and older

---

postgrest/base_client.py
postgrest/utils.py

- Check if `token` arg is a JWT string.
- Based (but not copied) from https://github.com/supabase/supabase-js/blob/6193a967a8d07605889446e9eabab149a275ee54/src/lib/helpers.ts#L75

feat: Check if token is a JWT

---

postgrest/base_request_builder.py

fix: head=True breaking count

---

postgrest/base_request_builder.py

Bug fix
Previously `columns` parameter of `def _cleaned_columns` was typed as "str", but actually tuple of strings was passed from `def pre_upsert`. 
The logic inside the function was also made for one string rather than for tuple of strings.
- The typing is changed to `columns: Tuple[str, ...]`
- Logic inside the function is fixed. Now each column-string is cleaned out of whitespaces.
My custom made test ran without errors:
```python
import unittest
from typing import Tuple
def _cleaned_columns(columns: Tuple[str, ...]) -> str:
quoted = False
cleaned = []
for column in columns:
clean_column = ""
for char in column:
if char.isspace() and not quoted:
continue
if char == '"':
quoted = not quoted
clean_column += char
cleaned.append(clean_column)
return ",".join(cleaned)
def wrap(*columns: …
```

fix: _cleaned_columns function now works with python multiline and typings

---

.github/workflows/ci.yml
postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py
tests/_async/test_filter_request_builder.py
tests/_async/test_query_request_builder.py
tests/_async/test_request_builder.py
tests/_sync/test_filter_request_builder.py
tests/_sync/test_query_request_builder.py
tests/_sync/test_request_builder.py

- Fix #560
- Fix body on HEAD.

fix: client is sending a body in a GET and HEAD requests

---

postgrest/_async/client.py
postgrest/_sync/client.py
postgrest/_sync/request_builder.py
postgrest/base_client.py
tests/_async/test_client.py
tests/_sync/test_client.py

The `.schema()` method from this library sets the schema as default, affecting the whole application instead of changing the schema of the current query only.

fix!: schema method persisting only on current query

---

infra/init.sql
postgrest/base_request_builder.py
tests/_async/test_filter_request_builder_integration.py
tests/_async/test_request_builder.py
tests/_sync/test_filter_request_builder_integration.py
tests/_sync/test_request_builder.py

Fix https://github.com/supabase/postgrest-py/issues/579

fix: order using foreign table

---

infra/init.sql
postgrest/_async/client.py
postgrest/_sync/client.py
postgrest/base_request_builder.py
tests/_sync/test_filter_request_builder_integration.py

Allows using GET and HEAD methods on Postgrest RPC functions with arguments.
RPC functions always try to send params in the body. This will fail for GET and HEAD methods.
https://github.com/supabase/postgrest-py/issues/592
You can now properly use get=True / head=True in postgrest RPC func calls.

fix: pass params as query params for get/head requests

---

Makefile
postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py
postgrest/exceptions.py
tests/_async/test_client.py
tests/_sync/test_client.py

Introduce validation that the error received on a request has the the correct JSON schema, as reported by #595.
Currently, if a request is not successful, it will try to convert its response to JSON by using `r.json()`, correctly ensuring that the `JSONDecodeError` is dealt with in the try block. However, given that `r.json()` returns `Any`, it is not guaranteed to be a `Dict[str, str]` as the `APIError.__init__()` method expects, and thus if an error response returns a valid non-dict JSON object, such as text surrounded by quotes (a valid JSON string) the initializer will throw an `AttributeError` when trying to access one of the JSON object's methods.
A simple `APIErrorFromJSON` pydantic model is introduced, to throw a `ValidationError` in the case of the response content not being …

fix: validate JSON input for APIError.__init__()

---

.pre-commit-config.yaml
poetry.lock
postgrest/_async/request_builder.py
postgrest/_sync/request_builder.py
postgrest/base_request_builder.py
pyproject.toml
tests/_async/test_client.py
tests/_async/test_filter_request_builder.py
tests/_async/test_query_request_builder.py
tests/_async/test_request_builder.py
tests/_sync/test_client.py
tests/_sync/test_filter_request_builder.py
tests/_sync/test_query_request_builder.py
tests/_sync/test_request_builder.py

Tooling update, replacing a bunch of dependencies with ruff which is faster and is quite compatible with the tools it replaces.

chore: replace isort, black, pyupgrade and autoflake with ruff
